-- ============================================================================
-- 기준 스키마 (2026-10-10 실제 DB에서 추출) — 이 저장소의 날짜별 마이그레이션은 2026-10-08 이후 변경분만 있어서
-- 그 전에 만든 표·정책·함수를 여기 한 번에 담음. 새 프로젝트에 올릴 때는 이 파일부터 적용하고 날짜 순으로 이어서 적용.
-- 이미 적용된 DB에는 다시 돌리지 않아도 됨 (create ... if not exists / or replace 로 되어 있어 돌려도 대부분 무해하나
-- 'create policy' 는 같은 이름이 있으면 실패함).
-- 주의: vault 비밀값(push_internal_key, callback_webhook_key)은 20261010_internal_secrets.sql 이 만듦.
-- 확장: pg_net, pg_cron, supabase_vault, pgcrypto (Supabase 기본)
-- ============================================================================

-- ===== 유형 =====
create type public.admin_role as enum ('pending', 'manager', 'master', 'owner', 'blocked', 'gongmu', 'pm', 'admin');

-- ===== 테이블 =====
create table if not exists public.admin_users (
  id uuid not null,
  email text not null,
  google_name text,
  staff_name text,
  role admin_role not null default 'pending'::admin_role,
  created_at timestamp with time zone not null default now(),
  approved_at timestamp with time zone,
  approved_by uuid,
  last_login_at timestamp with time zone
);

create table if not exists public.feedback (
  id bigint generated by default as identity,
  user_id uuid not null,
  kind text not null,
  body text not null,
  page text,
  ua text,
  platform text,
  standalone boolean,
  paths text[] not null default '{}'::text[],
  status text not null default 'open'::text,
  reply text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  pushed_at timestamp with time zone
);

create table if not exists public.holidays (
  day date not null,
  name text not null,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.jira_events (
  id bigint generated by default as identity,
  received_at timestamp with time zone not null default now(),
  event text,
  issue_key text,
  action text,
  bm_key text,
  ok boolean not null default true,
  error text,
  note text
);

create table if not exists public.message_files (
  id bigint generated by default as identity,
  message_id bigint not null,
  bm_key text not null,
  path text not null,
  name text not null,
  size bigint not null,
  mime text,
  width integer,
  height integer,
  created_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  deleted_reason text
);

create table if not exists public.message_reads (
  user_id uuid not null,
  bm_key text not null,
  last_read_at timestamp with time zone not null default now()
);

create table if not exists public.notification_prefs (
  user_id uuid not null,
  messages boolean not null default true,
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.owner_login_attempts (
  id bigint generated by default as identity,
  phone text,
  ip text,
  ok boolean not null,
  at timestamp with time zone not null default now()
);

create table if not exists public.owner_session_prefs (
  session_id uuid not null,
  user_id uuid not null,
  label text,
  updated_at timestamp with time zone not null default now(),
  device text
);

create table if not exists public.owner_sites (
  user_id uuid not null,
  bm_key text not null,
  linked_at timestamp with time zone not null default now()
);

create table if not exists public.owner_talk_sites (
  bm_key text not null,
  opened_at timestamp with time zone not null default now(),
  note text
);

create table if not exists public.owner_users (
  user_id uuid not null,
  phone text not null,
  name text,
  created_at timestamp with time zone not null default now(),
  last_login_at timestamp with time zone
);

create table if not exists public.preview_tickets (
  token text not null,
  bm_key text not null,
  created_by uuid not null,
  expires_at timestamp with time zone not null default (now() + '00:10:00'::interval)
);

create table if not exists public.push_config (
  key text not null,
  value text not null,
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity,
  user_id uuid not null,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  ua text,
  platform text,
  created_at timestamp with time zone not null default now(),
  last_seen_at timestamp with time zone not null default now(),
  fail_count integer not null default 0,
  owner_mode text not null default 'instant'::text,
  quiet text,
  last_push_at timestamp with time zone
);

create table if not exists public.site_messages (
  id bigint generated by default as identity,
  bm_key text not null,
  user_id uuid not null,
  sender_name text not null,
  sender_role text,
  body text not null,
  created_at timestamp with time zone not null default now(),
  target_role text,
  pushed_at timestamp with time zone,
  push_result text,
  channel text not null default 'staff'::text,
  call_owner boolean not null default false,
  sender_device text
);

create table if not exists public.sites (
  bm_key text not null,
  issue_name text,
  site_address text,
  owner_name text,
  phones text[] not null default '{}'::text[],
  manager text,
  designer text,
  interior text,
  bm_state text,
  contract_date date,
  movein_date date,
  ship_date date,
  start_date date,
  factory_type text,
  cost_total numeric,
  cost_paid numeric,
  cost_pct numeric,
  design_total numeric,
  design_paid numeric,
  design_pct numeric,
  ad_key text,
  ad_state text,
  fc_key text,
  fc_state text,
  ofb_key text,
  ofb_state text,
  ios_key text,
  ios_state text,
  cos_key text,
  cos_state text,
  asos_key text,
  asos_state text,
  shimdo_done_at timestamp with time zone,
  synced_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  archived_at timestamp with time zone,
  contract_no text,
  prefab_method text
);

create table if not exists public.staff (
  name text not null,
  phone text,
  role text,
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.stage_items (
  stage_key text not null,
  bm_key text not null,
  process text not null,
  name text not null,
  state text,
  seq integer,
  synced_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity,
  started_at timestamp with time zone not null default now(),
  finished_at timestamp with time zone,
  sites integer,
  items integer,
  note text
);

-- ===== 제약 =====
alter table public.admin_users add constraint admin_users_pkey PRIMARY KEY (id);
alter table public.feedback add constraint feedback_pkey PRIMARY KEY (id);
alter table public.holidays add constraint holidays_pkey PRIMARY KEY (day);
alter table public.jira_events add constraint jira_events_pkey PRIMARY KEY (id);
alter table public.message_files add constraint message_files_pkey PRIMARY KEY (id);
alter table public.message_reads add constraint message_reads_pkey PRIMARY KEY (user_id, bm_key);
alter table public.notification_prefs add constraint notification_prefs_pkey PRIMARY KEY (user_id);
alter table public.owner_login_attempts add constraint owner_login_attempts_pkey PRIMARY KEY (id);
alter table public.owner_session_prefs add constraint owner_session_prefs_pkey PRIMARY KEY (session_id);
alter table public.owner_sites add constraint owner_sites_pkey PRIMARY KEY (user_id, bm_key);
alter table public.owner_talk_sites add constraint owner_talk_sites_pkey PRIMARY KEY (bm_key);
alter table public.owner_users add constraint owner_users_pkey PRIMARY KEY (user_id);
alter table public.preview_tickets add constraint preview_tickets_pkey PRIMARY KEY (token);
alter table public.push_config add constraint push_config_pkey PRIMARY KEY (key);
alter table public.push_subscriptions add constraint push_subscriptions_pkey PRIMARY KEY (id);
alter table public.site_messages add constraint site_messages_pkey PRIMARY KEY (id);
alter table public.sites add constraint sites_pkey PRIMARY KEY (bm_key);
alter table public.staff add constraint staff_pkey PRIMARY KEY (name);
alter table public.stage_items add constraint stage_items_pkey PRIMARY KEY (stage_key);
alter table public.sync_runs add constraint sync_runs_pkey PRIMARY KEY (id);
alter table public.message_files add constraint message_files_path_key UNIQUE (path);
alter table public.owner_users add constraint owner_users_phone_key UNIQUE (phone);
alter table public.push_subscriptions add constraint push_subscriptions_endpoint_key UNIQUE (endpoint);
alter table public.feedback add constraint feedback_body_check CHECK ((length(body) <= 4000));
alter table public.feedback add constraint feedback_kind_check CHECK ((kind = ANY (ARRAY['bug'::text, 'improve'::text, 'question'::text])));
alter table public.feedback add constraint feedback_status_check CHECK ((status = ANY (ARRAY['open'::text, 'doing'::text, 'done'::text])));
alter table public.owner_session_prefs add constraint owner_session_prefs_device_check CHECK (((device IS NULL) OR (char_length(device) <= 60)));
alter table public.owner_session_prefs add constraint owner_session_prefs_label_check CHECK (((label IS NULL) OR ((char_length(label) >= 1) AND (char_length(label) <= 10))));
alter table public.push_subscriptions add constraint push_subscriptions_owner_mode_chk CHECK ((owner_mode = ANY (ARRAY['instant'::text, 'digest'::text, 'calls'::text])));
alter table public.push_subscriptions add constraint push_subscriptions_quiet_chk CHECK (((quiet IS NULL) OR (quiet = 'off'::text) OR (quiet ~ '^([01]?[0-9]|2[0-3])-([01]?[0-9]|2[0-3])$'::text)));
alter table public.site_messages add constraint site_messages_body_check CHECK ((length(body) <= 2000));
alter table public.site_messages add constraint site_messages_call_owner_check CHECK (((NOT call_owner) OR (channel = 'owner'::text)));
alter table public.site_messages add constraint site_messages_channel_check CHECK ((channel = ANY (ARRAY['staff'::text, 'owner'::text])));
alter table public.site_messages add constraint site_messages_sender_device_check CHECK (((sender_device IS NULL) OR (char_length(sender_device) <= 64)));
alter table public.site_messages add constraint site_messages_target_role_check CHECK (((target_role IS NULL) OR (target_role = ANY (ARRAY['영업'::text, '설계'::text, '인테리어'::text, '공무'::text, 'PM'::text]))));
alter table public.admin_users add constraint admin_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.feedback add constraint feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.message_files add constraint message_files_bm_key_fkey FOREIGN KEY (bm_key) REFERENCES sites(bm_key) ON DELETE CASCADE;
alter table public.message_files add constraint message_files_message_id_fkey FOREIGN KEY (message_id) REFERENCES site_messages(id) ON DELETE CASCADE;
alter table public.message_reads add constraint message_reads_bm_key_fkey FOREIGN KEY (bm_key) REFERENCES sites(bm_key) ON DELETE CASCADE;
alter table public.message_reads add constraint message_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notification_prefs add constraint notification_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.owner_session_prefs add constraint owner_session_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.owner_sites add constraint owner_sites_bm_key_fkey FOREIGN KEY (bm_key) REFERENCES sites(bm_key) ON DELETE CASCADE;
alter table public.owner_sites add constraint owner_sites_user_id_fkey FOREIGN KEY (user_id) REFERENCES owner_users(user_id) ON DELETE CASCADE;
alter table public.owner_talk_sites add constraint owner_talk_sites_bm_key_fkey FOREIGN KEY (bm_key) REFERENCES sites(bm_key) ON DELETE CASCADE;
alter table public.owner_users add constraint owner_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.push_subscriptions add constraint push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.site_messages add constraint site_messages_bm_key_fkey FOREIGN KEY (bm_key) REFERENCES sites(bm_key) ON DELETE CASCADE;
alter table public.site_messages add constraint site_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.stage_items add constraint stage_items_bm_key_fkey FOREIGN KEY (bm_key) REFERENCES sites(bm_key) ON DELETE CASCADE;

-- ===== 인덱스 =====
CREATE INDEX jira_events_received_at_idx ON public.jira_events USING btree (received_at DESC);
CREATE INDEX message_files_created_idx ON public.message_files USING btree (created_at) WHERE (deleted_at IS NULL);
CREATE INDEX message_files_message_idx ON public.message_files USING btree (message_id);
CREATE INDEX owner_login_attempts_ip_at ON public.owner_login_attempts USING btree (ip, at);
CREATE INDEX owner_login_attempts_phone_at ON public.owner_login_attempts USING btree (phone, at);
CREATE INDEX push_subscriptions_user_idx ON public.push_subscriptions USING btree (user_id);
CREATE INDEX site_messages_bm_channel_idx ON public.site_messages USING btree (bm_key, channel, created_at);
CREATE INDEX site_messages_bm_key_created_idx ON public.site_messages USING btree (bm_key, created_at);
CREATE INDEX sites_archived_idx ON public.sites USING btree (archived_at);
CREATE INDEX sites_bm_state_idx ON public.sites USING btree (bm_state);
CREATE INDEX sites_phones_gin ON public.sites USING gin (phones);
CREATE INDEX stage_items_bm_idx ON public.stage_items USING btree (bm_key);

-- ===== 함수 =====
-- 권한: 'revoke … from public, anon, authenticated' 뒤에 실제로 실행 가능한 역할만 grant. (grant 줄이 없으면 서비스 역할만)
CREATE OR REPLACE FUNCTION public.st_done(s text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
AS $function$ select lower(coalesce(s,'')) ~ '(완료|done|승인|납품)' $function$;

CREATE OR REPLACE FUNCTION public.st_skipped(s text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
AS $function$ select lower(coalesce(s,'')) ~ '(진행 안함|진행안함|won''t do|wont do)' $function$;

CREATE OR REPLACE FUNCTION public.is_approved()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce((select role in ('manager','owner','admin','gongmu','pm','master') from public.admin_users where id = auth.uid()), false)
$function$;

CREATE OR REPLACE FUNCTION public.is_full_access()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce((select role in ('owner','admin','gongmu','pm','master') from public.admin_users where id = auth.uid()), false)
$function$;

CREATE OR REPLACE FUNCTION public.is_owner_user()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ select exists (select 1 from public.owner_users where user_id = auth.uid()) $function$;

CREATE OR REPLACE FUNCTION public.my_admin_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select role::text from public.admin_users where id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.my_staff_name()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select nullif(trim(staff_name), '') from public.admin_users where id = auth.uid()
$function$;

CREATE OR REPLACE FUNCTION public.is_work_time(p_at timestamp with time zone DEFAULT now())
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with k as (select (p_at at time zone 'Asia/Seoul') as t)
  select extract(isodow from t) between 1 and 5
     and extract(hour from t) between 8 and 16
     and not exists (select 1 from public.holidays h where h.day = t::date)
  from k
$function$;

CREATE OR REPLACE FUNCTION public.next_open_at(p_t timestamp without time zone, p_maxdow integer, p_hour integer)
 RETURNS timestamp with time zone
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare d date := p_t::date;
begin
  if not (extract(hour from p_t) < p_hour and extract(isodow from d) <= p_maxdow
          and not exists (select 1 from public.holidays h where h.day = d)) then d := d + 1; end if;
  for i in 0..30 loop
    exit when extract(isodow from d) <= p_maxdow and not exists (select 1 from public.holidays h where h.day = d);
    d := d + 1;
  end loop;
  return (d + make_time(p_hour, 0, 0)) at time zone 'Asia/Seoul';
end $function$;

CREATE OR REPLACE FUNCTION public.work_status()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  t timestamp := now() at time zone 'Asia/Seoul';
  hol text;
  w boolean := public.is_work_time();
  s boolean;
  res jsonb;
begin
  select name into hol from public.holidays where day = t::date;
  s := hol is null and extract(isodow from t) <= 6 and extract(hour from t) between 9 and 17;
  res := jsonb_build_object('work', w, 'sales', s);
  if not w then
    res := res || jsonb_build_object('reason', case when hol is not null then 'holiday' when extract(isodow from t) > 5 then 'weekend' else 'hours' end,
                                     'holiday', hol, 'next', public.next_open_at(t, 5, 8));
  end if;
  if not s then res := res || jsonb_build_object('sales_next', public.next_open_at(t, 6, 9)); end if;
  return res;
end $function$;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if coalesce(new.raw_app_meta_data->>'kind', '') = 'owner'
     or lower(coalesce(new.email, '')) like '%@owner.invalid' then
    return new;
  end if;
  insert into public.admin_users (id, email, google_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    case when lower(coalesce(new.email,'')) = 'tareura@gmail.com' then 'owner'::public.admin_role else 'pending'::public.admin_role end
  )
  on conflict (id) do nothing;
  return new;
end
$function$;

CREATE OR REPLACE FUNCTION public.choose_staff_name(p_name text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.admin_users set staff_name = nullif(trim(p_name), '') where id = auth.uid() and role = 'pending';
end $function$;
revoke execute on function public.choose_staff_name(p_name text) from public, anon, authenticated;
grant execute on function public.choose_staff_name(p_name text) to authenticated;

CREATE OR REPLACE FUNCTION public.touch_login()
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  update public.admin_users set last_login_at = now() where id = auth.uid()
$function$;
revoke execute on function public.touch_login() from public, anon, authenticated;
grant execute on function public.touch_login() to authenticated;

CREATE OR REPLACE FUNCTION public.staff_accounts(p_names text[])
 RETURNS TABLE(name text, approved boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select n, exists (select 1 from public.admin_users a where trim(a.staff_name) = n and a.role in ('manager','owner','admin','gongmu','pm','master'))
  from unnest(p_names) as n where n is not null and n <> ''
$function$;
revoke execute on function public.staff_accounts(p_names text[]) from public, anon, authenticated;
grant execute on function public.staff_accounts(p_names text[]) to authenticated;

CREATE OR REPLACE FUNCTION public.staff_name_options()
 RETURNS TABLE(name text, roles text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select n, string_agg(distinct r, '·' order by r)
  from (
    select trim(manager) n, '영업' r from public.sites where manager is not null and manager <> '-'
    union all select trim(designer), '설계' from public.sites where designer is not null and designer <> '-'
    union all select trim(interior), '인테리어' from public.sites where interior is not null and interior <> '-'
  ) x where n <> '' group by n order by n
$function$;
revoke execute on function public.staff_name_options() from public, anon, authenticated;
grant execute on function public.staff_name_options() to authenticated;

CREATE OR REPLACE FUNCTION public.role_accounts()
 RETURNS TABLE(role text, n bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select role::text, count(*) from public.admin_users where role in ('gongmu','pm') group by role
$function$;

CREATE OR REPLACE FUNCTION public.lookup_sites(p_phone text)
 RETURNS SETOF sites
 LANGUAGE sql
 STABLE
AS $function$
  select * from public.sites where p_phone = any(phones) and archived_at is null order by bm_key
$function$;
revoke execute on function public.lookup_sites(p_phone text) from public, anon, authenticated;   -- 예전 번호 조회, 서버만

CREATE OR REPLACE FUNCTION public.finalize_sync(p_run_at timestamp with time zone)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_archived int; v_restored int; v_items int; v_purged int;
begin
  update public.sites set archived_at = now() where synced_at < p_run_at and archived_at is null;
  get diagnostics v_archived = row_count;
  update public.sites set archived_at = null where synced_at >= p_run_at and archived_at is not null;
  get diagnostics v_restored = row_count;
  delete from public.stage_items si where si.synced_at < p_run_at
    and exists (select 1 from public.sites s where s.bm_key = si.bm_key and s.archived_at is null);
  get diagnostics v_items = row_count;
  delete from public.sites where archived_at < now() - interval '5 years';
  get diagnostics v_purged = row_count;
  return jsonb_build_object('archived', v_archived, 'restored', v_restored, 'stale_items_deleted', v_items, 'purged_5y', v_purged);
end $function$;
revoke execute on function public.finalize_sync(p_run_at timestamp with time zone) from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.norm_phones(p text[])
 RETURNS text[]
 LANGUAGE sql
 IMMUTABLE
AS $function$
  select coalesce(array_agg(x order by ord), '{}'::text[]) from (
    select x, min(ord) ord from (
      select raw.ord, parts.x from (
        select regexp_replace(coalesce(v, ''), '[^0-9]', '', 'g') d, ord from unnest(p) with ordinality u(v, ord)
      ) raw
      cross join lateral (
        select unnest(case
          when length(raw.d) > 11 and raw.d ~ '^(01\d{9})+$' then regexp_split_to_array(regexp_replace(raw.d, '(01\d{9})', '\1,', 'g'), ',')   -- 11자리 휴대폰이 이어 붙음
          when length(raw.d) > 10 and raw.d ~ '^(01\d{8})+$' then regexp_split_to_array(regexp_replace(raw.d, '(01\d{8})', '\1,', 'g'), ',')   -- 10자리(011 등)가 이어 붙음
          else array[raw.d] end) as x
      ) parts
      where parts.x <> ''
    ) s
    group by x
  ) t
$function$;

CREATE OR REPLACE FUNCTION public.sites_norm_phones()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.phones := public.norm_phones(new.phones);
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.chat_active_roles(p_bm_key text)
 RETURNS text[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with items as (
    select process, name, state from public.stage_items
    where bm_key = p_bm_key and not public.st_skipped(state)
  ),
  ad as (select name, state from items where process = 'AD'),
  shim as (select count(*) n, count(*) filter (where public.st_done(state)) d from ad where name like '%실시도면%' or name like '%실시설계%'),
  all_ad as (select count(*) n, count(*) filter (where public.st_done(state)) d from ad),
  s as (select bm_state, cost_pct from public.sites where bm_key = p_bm_key),
  past as (
    select coalesce((select bm_state ~ '설계|변경계약|착공|설치' from s), false)
        or coalesce((select cost_pct >= 85 from s), false)
        or exists (select 1 from items where public.st_done(state) or state ~* '(시공 ?중|진행 ?중|in progress|접수)') as v
  )
  select array_remove(array[
    case when not past.v then '영업' end,
    case when not (shim.n > 0 and shim.d = shim.n) then '설계' end,
    case when not (all_ad.n > 0 and all_ad.d = all_ad.n) then '인테리어' end
  ]::text[], null)
  from shim, all_ad, past
$function$;

CREATE OR REPLACE FUNCTION public.owner_has_site(p_bm_key text, p_write boolean DEFAULT false)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.owner_sites os
    join public.owner_talk_sites t on t.bm_key = os.bm_key
    join public.sites s on s.bm_key = os.bm_key
    where os.user_id = auth.uid() and os.bm_key = p_bm_key
      and (not p_write or s.archived_at is null)
  )
$function$;

CREATE OR REPLACE FUNCTION public.owner_can_read_file(p_path text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.message_files f
    join public.site_messages m on m.id = f.message_id
    where f.path = p_path and m.channel = 'owner' and public.owner_has_site(m.bm_key)
  )
$function$;

CREATE OR REPLACE FUNCTION public.owner_message_sender()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare nm text; lb text; au record; s record; allowed text[];
begin
  select name into nm from public.owner_users where user_id = new.user_id;
  if found then
    select label into lb from public.owner_session_prefs
     where session_id = nullif(auth.jwt()->>'session_id', '')::uuid and user_id = new.user_id;
    new.sender_name := coalesce(nullif(trim(nm), ''), '건축주') || coalesce(' (' || nullif(nullif(trim(lb), ''), '본인') || ')', '');
    new.sender_role := '건축주';
    return new;
  end if;
  select staff_name, google_name, email, role::text as role into au from public.admin_users where id = new.user_id;
  if found then
    new.sender_name := coalesce(nullif(trim(au.staff_name), ''), nullif(trim(au.google_name), ''), au.email, '직원');
    select manager, designer, interior into s from public.sites where bm_key = new.bm_key;
    allowed := array_remove(array[
      case when au.staff_name is not null and trim(coalesce(s.manager, ''))  = trim(au.staff_name) then '영업' end,
      case when au.staff_name is not null and trim(coalesce(s.designer, '')) = trim(au.staff_name) then '설계' end,
      case when au.staff_name is not null and trim(coalesce(s.interior, '')) = trim(au.staff_name) then '인테리어' end,
      case au.role when 'manager' then '담당자' when 'gongmu' then '공무' when 'pm' then 'PM' when 'admin' then '관리자'
                   when 'master' then '마스터(구)' when 'owner' then '운영자' end
    ], null);
    if new.sender_role is null or not (new.sender_role = any(allowed)) then
      new.sender_role := coalesce(allowed[1], '직원');
    end if;
  end if;
  return new;
end $function$;
revoke execute on function public.owner_message_sender() from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.mark_read(p_bm_key text)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  insert into public.message_reads (user_id, bm_key, last_read_at) values (auth.uid(), p_bm_key, now())
  on conflict (user_id, bm_key) do update set last_read_at = now()
$function$;
revoke execute on function public.mark_read(p_bm_key text) from public, anon, authenticated;
grant execute on function public.mark_read(p_bm_key text) to authenticated;

CREATE OR REPLACE FUNCTION public.unread_counts()
 RETURNS TABLE(bm_key text, n bigint, calls bigint)
 LANGUAGE sql
 STABLE
AS $function$
  with me as (select public.my_staff_name() as nm, public.my_admin_role() as rl)
  select m.bm_key,
         count(*) as n,
         count(*) filter (where m.target_role is not null and (
             (m.target_role = '영업'     and trim(coalesce(s.manager,''))  = me.nm) or
             (m.target_role = '설계'     and trim(coalesce(s.designer,'')) = me.nm) or
             (m.target_role = '인테리어' and trim(coalesce(s.interior,'')) = me.nm) or
             (m.target_role = '공무'     and me.rl = 'gongmu') or
             (m.target_role = 'PM'       and me.rl = 'pm'))) as calls
  from public.site_messages m
  join public.sites s on s.bm_key = m.bm_key
  cross join me
  left join public.message_reads r on r.bm_key = m.bm_key and r.user_id = auth.uid()
  where m.user_id <> auth.uid() and (r.last_read_at is null or m.created_at > r.last_read_at)
  group by m.bm_key
$function$;
revoke execute on function public.unread_counts() from public, anon, authenticated;
grant execute on function public.unread_counts() to authenticated;

CREATE OR REPLACE FUNCTION public.push_recipients(p_message_id bigint)
 RETURNS TABLE(user_id uuid, sub_id bigint, endpoint text, p256dh text, auth text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with m as (select * from public.site_messages where id = p_message_id),
  s as (select s.* from public.sites s join m on s.bm_key = m.bm_key),
  roles as (
    select unnest(case when m.target_role is not null then array[m.target_role]
                       else public.chat_active_roles(m.bm_key) end) as r
    from m
  ),
  names as (
    select distinct nullif(trim(case roles.r when '영업' then s.manager when '설계' then s.designer when '인테리어' then s.interior end), '') as nm
    from roles, s
  ),
  users as (
    select a.id
    from public.admin_users a
    join names on trim(coalesce(a.staff_name, '')) = names.nm
    where names.nm is not null
      and a.role in ('manager','owner','admin','gongmu','pm','master')
      and a.id is distinct from (select user_id from m)
      and ((select target_role from m) is not null
           or coalesce((select p.messages from public.notification_prefs p where p.user_id = a.id), true))
    union
    select a.id
    from public.admin_users a, m
    where ((m.target_role = '공무' and a.role = 'gongmu') or (m.target_role = 'PM' and a.role = 'pm'))
      and a.id is distinct from m.user_id
    union
    -- 건축주톡: 그 현장에 연결된 건축주 (공간 Talk가 열려 있을 때만)
    select os.user_id
    from public.owner_sites os
    join m on m.bm_key = os.bm_key and m.channel = 'owner'
    join public.owner_talk_sites t on t.bm_key = os.bm_key
    where os.user_id is distinct from m.user_id
  )
  select ps.user_id, ps.id, ps.endpoint, ps.p256dh, ps.auth
  from public.push_subscriptions ps
  join users u on u.id = ps.user_id
$function$;
revoke execute on function public.push_recipients(p_message_id bigint) from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.digest_pending()
 RETURNS TABLE(user_id uuid, n bigint, sites bigint, calls bigint)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with d as (
    select m.id, m.bm_key, m.created_at, m.target_role
    from public.site_messages m
    where m.pushed_at is null and m.push_result = 'deferred'
  ),
  r as (
    select d.id, d.bm_key, d.created_at, d.target_role, p.user_id
    from d cross join lateral public.push_recipients(d.id) p
  ),
  u as (
    select distinct r.id, r.bm_key, r.user_id, r.target_role
    from r
    left join public.message_reads mr on mr.user_id = r.user_id and mr.bm_key = r.bm_key
    where mr.last_read_at is null or r.created_at > mr.last_read_at
  )
  select u.user_id, count(distinct u.id), count(distinct u.bm_key), count(distinct u.id) filter (where u.target_role is not null)
  from u group by u.user_id
$function$;
revoke execute on function public.digest_pending() from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.owner_digest_due(p_hour integer)
 RETURNS TABLE(sub_id bigint, user_id uuid, endpoint text, p256dh text, auth text, n bigint, calls bigint, sites bigint, one_site text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with subs as (
    select ps.*, coalesce(ps.quiet, '21-8') as q
    from public.push_subscriptions ps join public.owner_users ou on ou.user_id = ps.user_id
  ), due as (
    select * from subs
    where (owner_mode = 'digest' and p_hour = 8)
       or (owner_mode in ('instant', 'calls') and q <> 'off' and split_part(q, '-', 1) <> split_part(q, '-', 2)
           and split_part(q, '-', 2)::int = p_hour)
  )
  select d.id, d.user_id, d.endpoint, d.p256dh, d.auth,
         count(distinct m.id), count(distinct m.id) filter (where m.call_owner), count(distinct m.bm_key), min(m.bm_key)
  from due d
  join public.owner_sites os on os.user_id = d.user_id
  join public.owner_talk_sites t on t.bm_key = os.bm_key
  join public.site_messages m on m.bm_key = os.bm_key and m.channel = 'owner'
   and m.created_at > greatest(coalesce(d.last_push_at, d.created_at), now() - interval '3 days')
   and m.user_id is distinct from d.user_id and m.sender_role is distinct from '건축주'
   and (d.owner_mode <> 'calls' or m.call_owner)
  group by d.id, d.user_id, d.endpoint, d.p256dh, d.auth
  having count(distinct m.id) > 0
$function$;
revoke execute on function public.owner_digest_due(p_hour integer) from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.push_fail(p_id bigint)
 RETURNS void
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with u as (update public.push_subscriptions set fail_count = fail_count + 1 where id = p_id returning id, fail_count)
  delete from public.push_subscriptions where id in (select id from u where fail_count >= 8)
$function$;
revoke execute on function public.push_fail(p_id bigint) from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.push_status()
 RETURNS TABLE(user_id uuid, devices bigint, platforms text[], last_seen_at timestamp with time zone, messages boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select a.id,
         count(ps.id),
         coalesce(array_agg(distinct ps.platform) filter (where ps.platform is not null), '{}'),
         max(ps.last_seen_at),
         coalesce((select p.messages from public.notification_prefs p where p.user_id = a.id), true)
  from public.admin_users a
  left join public.push_subscriptions ps on ps.user_id = a.id
  where public.my_admin_role() = 'owner'
  group by a.id
$function$;

CREATE OR REPLACE FUNCTION public.storage_usage()
 RETURNS bigint
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(sum(size), 0) from public.message_files where deleted_at is null
$function$;
revoke execute on function public.storage_usage() from public, anon, authenticated;
grant execute on function public.storage_usage() to authenticated;

CREATE OR REPLACE FUNCTION public.orphan_chat_files()
 RETURNS TABLE(path text, created_at timestamp with time zone)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'storage'
AS $function$
  select o.name, o.created_at
  from storage.objects o
  where o.bucket_id = 'chat-files'
    and o.created_at < now() - interval '1 hour'
    and not exists (select 1 from public.message_files f where f.path = o.name)
  order by o.created_at
  limit 500
$function$;
revoke execute on function public.orphan_chat_files() from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.owner_devices()
 RETURNS TABLE(session_id uuid, created_at timestamp with time zone, last_active timestamp with time zone, user_agent text, label text, is_current boolean)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select s.id, s.created_at, coalesce(s.refreshed_at at time zone 'UTC', s.updated_at), p.device, p.label,
         s.id = nullif(auth.jwt()->>'session_id', '')::uuid
  from auth.sessions s
  left join public.owner_session_prefs p on p.session_id = s.id
  where s.user_id = auth.uid() and public.is_owner_user()
    and (s.not_after is null or s.not_after > now())
    and coalesce(s.refreshed_at at time zone 'UTC', s.updated_at, s.created_at) > now() - interval '60 days'
  order by 6 desc, 3 desc nulls last
$function$;
revoke execute on function public.owner_devices() from public, anon, authenticated;
grant execute on function public.owner_devices() to authenticated;

CREATE OR REPLACE FUNCTION public.site_bundle(p_keys text[])
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'sites', coalesce((select jsonb_agg((to_jsonb(s) - 'contract_no') order by s.bm_key) from public.sites s where s.bm_key = any(p_keys) and s.archived_at is null), '[]'::jsonb),
    'stages', coalesce((select jsonb_agg(jsonb_build_object('bm_key', i.bm_key, 'process', i.process, 'stage_key', i.stage_key, 'name', i.name, 'state', i.state, 'seq', i.seq) order by i.bm_key, i.seq)
                        from public.stage_items i where i.bm_key = any(p_keys)), '[]'::jsonb),
    -- 영업·인테리어 담당자 번호만 (건축주 앱의 전화 연결용)
    'staff', coalesce((select jsonb_object_agg(st.name, st.phone) from public.staff st
                       where st.name in (select trim(x) from public.sites s, unnest(array[s.manager, s.interior]) x where s.bm_key = any(p_keys) and x is not null)), '{}'::jsonb)
  )
$function$;
revoke execute on function public.site_bundle(p_keys text[]) from public, anon, authenticated;

CREATE OR REPLACE FUNCTION public.owner_dashboard()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select case when public.is_owner_user()
    then public.site_bundle(array(select os.bm_key from public.owner_sites os where os.user_id = auth.uid()))
         || jsonb_build_object('more', (
              select count(*) from public.sites s, public.owner_users ou
              where ou.user_id = auth.uid() and ou.phone = any(s.phones) and s.archived_at is null
                and not exists (select 1 from public.owner_sites os where os.user_id = auth.uid() and os.bm_key = s.bm_key)))
    else null end
$function$;
revoke execute on function public.owner_dashboard() from public, anon, authenticated;
grant execute on function public.owner_dashboard() to authenticated;

CREATE OR REPLACE FUNCTION public.create_preview_ticket(p_bm_key text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare t text := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');
begin
  if not public.is_approved() then raise exception 'not allowed'; end if;
  if not exists (
    select 1 from public.sites s
    where s.bm_key = p_bm_key and s.archived_at is null
      and (public.is_full_access()
           or (public.my_admin_role() = 'manager' and public.my_staff_name() is not null
               and public.my_staff_name() in (trim(coalesce(s.manager, '')), trim(coalesce(s.designer, '')), trim(coalesce(s.interior, '')))))
  ) then raise exception 'not allowed'; end if;
  insert into public.preview_tickets (token, bm_key, created_by) values (t, p_bm_key, auth.uid());
  return t;
end $function$;
revoke execute on function public.create_preview_ticket(p_bm_key text) from public, anon, authenticated;
grant execute on function public.create_preview_ticket(p_bm_key text) to authenticated;

CREATE OR REPLACE FUNCTION public.preview_bundle(p_token text)
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select public.site_bundle(array[t.bm_key]) from public.preview_tickets t where t.token = p_token and t.expires_at > now()
$function$;

CREATE OR REPLACE FUNCTION public.internal_secret(p_name text)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$ select decrypted_secret from vault.decrypted_secrets where name = p_name limit 1 $function$;
revoke execute on function public.internal_secret(p_name text) from public, anon, authenticated;
grant execute on function public.internal_secret(p_name text) to service_role;

CREATE OR REPLACE FUNCTION public.notify_push_on_message()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform net.http_post(
    url := 'https://ljxonejavjagwqrorfui.supabase.co/functions/v1/send-push',
    body := jsonb_build_object('message_id', new.id),
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-internal-key', public.internal_secret('push_internal_key')),
    timeout_milliseconds := 8000);
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.notify_push_on_feedback()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if tg_op = 'INSERT' then
    perform net.http_post(
      url := 'https://ljxonejavjagwqrorfui.supabase.co/functions/v1/send-push',
      body := jsonb_build_object('feedback_id', new.id),
      headers := jsonb_build_object('Content-Type', 'application/json', 'x-internal-key', public.internal_secret('push_internal_key')),
      timeout_milliseconds := 8000);
  elsif (old.status is distinct from new.status) or (old.reply is distinct from new.reply) then
    new.updated_at := now();
    perform net.http_post(
      url := 'https://ljxonejavjagwqrorfui.supabase.co/functions/v1/send-push',
      body := jsonb_build_object('feedback_id', new.id, 'event', 'reply'),
      headers := jsonb_build_object('Content-Type', 'application/json', 'x-internal-key', public.internal_secret('push_internal_key')),
      timeout_milliseconds := 8000);
  end if;
  return new;
end $function$;

-- ===== RLS =====
alter table public.admin_users enable row level security;
alter table public.feedback enable row level security;
alter table public.holidays enable row level security;
alter table public.jira_events enable row level security;
alter table public.message_files enable row level security;
alter table public.message_reads enable row level security;
alter table public.notification_prefs enable row level security;
alter table public.owner_login_attempts enable row level security;
alter table public.owner_session_prefs enable row level security;
alter table public.owner_sites enable row level security;
alter table public.owner_talk_sites enable row level security;
alter table public.owner_users enable row level security;
alter table public.preview_tickets enable row level security;
alter table public.push_config enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.site_messages enable row level security;
alter table public.sites enable row level security;
alter table public.staff enable row level security;
alter table public.stage_items enable row level security;
alter table public.sync_runs enable row level security;

-- ===== 정책 =====
-- (정책이 없는 표: owner_login_attempts, preview_tickets, push_config → 서비스 역할·함수로만 다룸)
create policy "owner read all" on public.admin_users as permissive for SELECT to authenticated using ((my_admin_role() = 'owner'::text));
create policy "owner update" on public.admin_users as permissive for UPDATE to authenticated using ((my_admin_role() = 'owner'::text)) with check ((my_admin_role() = 'owner'::text));
create policy "self read" on public.admin_users as permissive for SELECT to authenticated using ((id = auth.uid()));
create policy "feedback insert own" on public.feedback as permissive for INSERT to public with check (((user_id = auth.uid()) AND is_approved()));
create policy "feedback owner update" on public.feedback as permissive for UPDATE to public using ((my_admin_role() = 'owner'::text)) with check ((my_admin_role() = 'owner'::text));
create policy "feedback read own or owner" on public.feedback as permissive for SELECT to public using (((user_id = auth.uid()) OR (my_admin_role() = 'owner'::text)));
create policy "owner app inquiry insert" on public.feedback as permissive for INSERT to public with check (((user_id = auth.uid()) AND is_owner_user() AND (kind = 'question'::text) AND (COALESCE(status, 'open'::text) = 'open'::text) AND (reply IS NULL) AND (pushed_at IS NULL) AND (COALESCE(paths, '{}'::text[]) = '{}'::text[])));
create policy "approved read holidays" on public.holidays as permissive for SELECT to public using (is_approved());
create policy "owner write holidays" on public.holidays as permissive for ALL to public using ((my_admin_role() = 'owner'::text)) with check ((my_admin_role() = 'owner'::text));
create policy "owner read events" on public.jira_events as permissive for SELECT to authenticated using ((my_admin_role() = 'owner'::text));
create policy "insert files to own message" on public.message_files as permissive for INSERT to authenticated with check ((is_approved() AND (EXISTS ( SELECT 1
   FROM site_messages m
  WHERE ((m.id = message_files.message_id) AND (m.user_id = auth.uid()))))));
create policy "owner inserts files to own talk message" on public.message_files as permissive for INSERT to public with check ((EXISTS ( SELECT 1
   FROM site_messages m
  WHERE ((m.id = message_files.message_id) AND (m.user_id = auth.uid()) AND (m.channel = 'owner'::text)))));
create policy "owner reads talk files" on public.message_files as permissive for SELECT to public using ((owner_has_site(bm_key) AND (EXISTS ( SELECT 1
   FROM site_messages m
  WHERE ((m.id = message_files.message_id) AND (m.channel = 'owner'::text))))));
create policy "read files of visible sites" on public.message_files as permissive for SELECT to authenticated using ((is_approved() AND (EXISTS ( SELECT 1
   FROM sites s
  WHERE (s.bm_key = message_files.bm_key)))));
create policy "own reads insert" on public.message_reads as permissive for INSERT to authenticated with check ((user_id = auth.uid()));
create policy "own reads select" on public.message_reads as permissive for SELECT to authenticated using ((user_id = auth.uid()));
create policy "own reads update" on public.message_reads as permissive for UPDATE to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "own prefs" on public.notification_prefs as permissive for ALL to public using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "owner own session prefs" on public.owner_session_prefs as permissive for ALL to public using (((user_id = auth.uid()) AND is_owner_user())) with check (((user_id = auth.uid()) AND is_owner_user() AND (session_id = (NULLIF((auth.jwt() ->> 'session_id'::text), ''::text))::uuid)));
create policy "owner reads own links or staff reads" on public.owner_sites as permissive for SELECT to public using (((user_id = auth.uid()) OR is_approved()));
create policy "anyone reads owner talk sites" on public.owner_talk_sites as permissive for SELECT to anon, authenticated using (true);
create policy "owner manages owner talk sites" on public.owner_talk_sites as permissive for ALL to authenticated using ((my_admin_role() = 'owner'::text)) with check ((my_admin_role() = 'owner'::text));
create policy "owner reads self or staff reads" on public.owner_users as permissive for SELECT to public using (((user_id = auth.uid()) OR is_approved()));
create policy "own subscriptions" on public.push_subscriptions as permissive for ALL to public using (((user_id = auth.uid()) AND is_approved())) with check (((user_id = auth.uid()) AND is_approved()));
create policy "owner own push subscriptions" on public.push_subscriptions as permissive for ALL to public using (((user_id = auth.uid()) AND is_owner_user())) with check (((user_id = auth.uid()) AND is_owner_user()));
create policy "delete own recent message" on public.site_messages as permissive for DELETE to authenticated using (((user_id = auth.uid()) AND (created_at > (now() - '00:05:00'::interval))));
create policy "owner reads own talk" on public.site_messages as permissive for SELECT to public using (((channel = 'owner'::text) AND owner_has_site(bm_key)));
create policy "owner writes own talk" on public.site_messages as permissive for INSERT to public with check (((channel = 'owner'::text) AND (user_id = auth.uid()) AND (NOT call_owner) AND owner_has_site(bm_key, true)));
create policy "read messages of visible sites" on public.site_messages as permissive for SELECT to authenticated using ((is_approved() AND (EXISTS ( SELECT 1
   FROM sites s
  WHERE (s.bm_key = site_messages.bm_key)))));
create policy "write messages to visible sites" on public.site_messages as permissive for INSERT to authenticated with check ((is_approved() AND (user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM sites s
  WHERE ((s.bm_key = site_messages.bm_key) AND (s.archived_at IS NULL)))) AND ((channel = 'staff'::text) OR (EXISTS ( SELECT 1
   FROM owner_talk_sites o
  WHERE (o.bm_key = site_messages.bm_key))))));
create policy "admin read sites" on public.sites as permissive for SELECT to public using ((is_full_access() OR ((my_admin_role() = 'manager'::text) AND (my_staff_name() IS NOT NULL) AND ((my_staff_name() = TRIM(BOTH FROM COALESCE(manager, ''::text))) OR (my_staff_name() = TRIM(BOTH FROM COALESCE(designer, ''::text))) OR (my_staff_name() = TRIM(BOTH FROM COALESCE(interior, ''::text)))))));
create policy "approved read staff" on public.staff as permissive for SELECT to authenticated using (is_approved());
create policy "admin read items" on public.stage_items as permissive for SELECT to authenticated using ((EXISTS ( SELECT 1
   FROM sites s
  WHERE (s.bm_key = stage_items.bm_key))));
create policy "approved read runs" on public.sync_runs as permissive for SELECT to authenticated using (is_approved());

-- ===== 트리거 =====
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();
CREATE TRIGGER feedback_push_insert AFTER INSERT ON public.feedback FOR EACH ROW EXECUTE FUNCTION notify_push_on_feedback();
CREATE TRIGGER feedback_push_update BEFORE UPDATE ON public.feedback FOR EACH ROW EXECUTE FUNCTION notify_push_on_feedback();
CREATE TRIGGER site_messages_owner_sender BEFORE INSERT ON public.site_messages FOR EACH ROW EXECUTE FUNCTION owner_message_sender();
CREATE TRIGGER site_messages_push AFTER INSERT ON public.site_messages FOR EACH ROW EXECUTE FUNCTION notify_push_on_message();
CREATE TRIGGER sites_norm_phones BEFORE INSERT OR UPDATE OF phones ON public.sites FOR EACH ROW EXECUTE FUNCTION sites_norm_phones();

-- ===== cron =====
select cron.schedule('push-digest', '30 23 * * *', $cron$ select net.http_post(
       url := 'https://ljxonejavjagwqrorfui.supabase.co/functions/v1/send-push',
       body := '{"digest":true}'::jsonb,
       headers := jsonb_build_object('Content-Type', 'application/json', 'x-internal-key', public.internal_secret('push_internal_key')),
       timeout_milliseconds := 8000) $cron$);
select cron.schedule('owner-push-digest', '2 * * * *', $cron$ select net.http_post(
       url := 'https://ljxonejavjagwqrorfui.supabase.co/functions/v1/send-push',
       body := '{"owner_digest":true}'::jsonb,
       headers := jsonb_build_object('Content-Type', 'application/json', 'x-internal-key', public.internal_secret('push_internal_key')),
       timeout_milliseconds := 8000) $cron$);

-- ===== storage =====
insert into storage.buckets (id, name, public, file_size_limit) values ('chat-files', 'chat-files', false, 10485760) on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit) values ('feedback-files', 'feedback-files', false, 10485760) on conflict (id) do nothing;
create policy "chat files delete own recent" on storage.objects as permissive for DELETE to authenticated using (((bucket_id = 'chat-files'::text) AND (owner = auth.uid()) AND (created_at > (now() - '00:05:00'::interval))));
create policy "chat files owner read" on storage.objects as permissive for SELECT to public using (((bucket_id = 'chat-files'::text) AND owner_can_read_file(name)));
create policy "chat files owner upload" on storage.objects as permissive for INSERT to public with check (((bucket_id = 'chat-files'::text) AND owner_has_site(split_part(name, '/'::text, 1), true)));
create policy "chat files read" on storage.objects as permissive for SELECT to authenticated using (((bucket_id = 'chat-files'::text) AND is_approved() AND (EXISTS ( SELECT 1
   FROM sites s
  WHERE (s.bm_key = split_part(objects.name, '/'::text, 1))))));
create policy "chat files upload" on storage.objects as permissive for INSERT to authenticated with check (((bucket_id = 'chat-files'::text) AND is_approved() AND (EXISTS ( SELECT 1
   FROM sites s
  WHERE ((s.bm_key = split_part(objects.name, '/'::text, 1)) AND (s.archived_at IS NULL))))));
create policy "feedback files read" on storage.objects as permissive for SELECT to public using (((bucket_id = 'feedback-files'::text) AND ((split_part(name, '/'::text, 1) = (auth.uid())::text) OR (my_admin_role() = 'owner'::text))));
create policy "feedback files upload" on storage.objects as permissive for INSERT to public with check (((bucket_id = 'feedback-files'::text) AND is_approved() AND (split_part(name, '/'::text, 1) = (auth.uid())::text)));
