-- 1) 관리자 앱 '최근 대화 순': 현장별 마지막 메시지 (호출한 직원이 볼 수 있는 현장만 — security invoker라 RLS 그대로)
create or replace function public.site_last_messages()
returns table(bm_key text, last_at timestamptz, sender_name text, sender_role text, channel text, body text, has_file boolean)
language sql stable security invoker set search_path to 'public'
as $$
  select distinct on (m.bm_key) m.bm_key, m.created_at, m.sender_name, m.sender_role, m.channel, left(m.body, 80),
         exists (select 1 from public.message_files f where f.message_id = m.id)
  from public.site_messages m
  order by m.bm_key, m.created_at desc
$$;
revoke execute on function public.site_last_messages() from public, anon;
grant execute on function public.site_last_messages() to authenticated;

-- 2) 서류함 (관리자 앱 내부용): 현장별 계약서·도면 등. 지금은 직원이 직접 올림(source='upload'),
--    나중에 Jira 첨부를 가져오면 source='jira' + jira_attachment_id 로 중복 없이 넣을 수 있게 열을 둠
create table if not exists public.site_docs (
  id bigint generated by default as identity primary key,
  bm_key text not null references public.sites(bm_key) on delete cascade,
  kind text not null default '기타' check (kind in ('계약서', '변경계약서', '도면', '인허가', '기타')),
  name text not null check (char_length(name) between 1 and 200),
  path text not null unique,
  size bigint not null,
  mime text,
  note text check (note is null or char_length(note) <= 200),
  source text not null default 'upload' check (source in ('upload', 'jira')),
  jira_attachment_id text unique,
  uploaded_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists site_docs_bm_idx on public.site_docs (bm_key, created_at desc);
alter table public.site_docs enable row level security;
create policy "staff read docs of visible sites" on public.site_docs for select to authenticated
  using (public.is_approved() and exists (select 1 from public.sites s where s.bm_key = site_docs.bm_key));
create policy "staff upload docs to visible sites" on public.site_docs for insert to authenticated
  with check (public.is_approved() and uploaded_by = (select auth.uid()) and source = 'upload'
              and exists (select 1 from public.sites s where s.bm_key = site_docs.bm_key and s.archived_at is null));
create policy "uploader or admin deletes docs" on public.site_docs for delete to authenticated
  using (public.is_approved() and (uploaded_by = (select auth.uid()) or public.my_admin_role() in ('owner', 'admin')));

insert into storage.buckets (id, name, public, file_size_limit) values ('site-docs', 'site-docs', false, 52428800)
on conflict (id) do nothing;
create policy "site docs read" on storage.objects for select to authenticated
  using (bucket_id = 'site-docs' and public.is_approved() and exists (select 1 from public.sites s where s.bm_key = split_part(objects.name, '/', 1)));
create policy "site docs upload" on storage.objects for insert to authenticated
  with check (bucket_id = 'site-docs' and public.is_approved() and exists (select 1 from public.sites s where s.bm_key = split_part(objects.name, '/', 1) and s.archived_at is null));
create policy "site docs delete" on storage.objects for delete to authenticated
  using (bucket_id = 'site-docs' and public.is_approved() and (owner = (select auth.uid()) or public.my_admin_role() in ('owner', 'admin')));

-- 3) 실시간: 새 메시지·첨부를 앱에 바로 보냄 (받는 쪽 RLS 그대로 적용 — 볼 수 있는 메시지만 옴)
alter publication supabase_realtime add table public.site_messages, public.message_files;

-- 4) 공사 단계 변경 알림 (건축주): 현장별 마지막으로 본 단계 + 기기별 보낸 기록 (서비스 역할만 사용)
create table if not exists public.site_stage (
  bm_key text primary key references public.sites(bm_key) on delete cascade,
  stage_id text not null,
  stage_idx int not null,
  title text not null,
  changed_at timestamptz,          -- 앞 단계로 넘어간 시각 (처음 본 현장·뒤로 간 경우는 null → 알림 없음)
  checked_at timestamptz not null default now()
);
create table if not exists public.stage_push_log (
  bm_key text not null,
  stage_id text not null,
  sub_id bigint not null references public.push_subscriptions(id) on delete cascade,
  sent_at timestamptz not null default now(),
  primary key (bm_key, stage_id, sub_id)
);
alter table public.site_stage enable row level security;
alter table public.stage_push_log enable row level security;
